import ImageCard from "../ui/ImageCard";

const cardItems = [
    {
        head: 'Thorough Documentation',
        body: "Be comprehensive in documenting the patient encounter. Include a detailed history of present illness, an exhaustive examination, and a comprehensive medical decision-making process. Capture all relevant details, ensuring that your notes paint a complete picture of the patient's condition and your clinical assessment",
        imgUrl: 'src/assets/codeAccuracy/image1.png',
    },
    {
        head: 'Assess Risk and Complexity',
        body: "Evaluate and document the risk of complications and/or morbidity associated with the patient's condition. Be explicit about the factors contributing to the complexity of the case. The goCPT app considers risk assessment, and detailed documentation aids in accurate code generation",
        imgUrl: 'src/assets/codeAccuracy/image2.png',
    },
    {
        head: 'Time-Based Coding',
        body: "Utilize time-based coding when appropriate. If a significant portion of the encounter is devoted to counseling or coordination of care, document the time spent. The goCPT app recognizes time as a crucial factor in certain code selections, contributing to accurate billing",
        imgUrl: 'src/assets/codeAccuracy/image3.png',
    },
    {
        head: 'Specificity Matters',
        body: "Provide specific details about each medical issue. Describe the nature, severity, and progression of symptoms. Specificity enhances the accuracy of code generation by ensuring that the app captures the complexity of the patient's conditions and the level of decision-making required",
        imgUrl: 'src/assets/codeAccuracy/image4.png',
    },
    {
        head: 'Include Relevant Data',
        body: "Ensure that your note incorporates all relevant data, including diagnostic test results, imaging studies, and laboratory findings. The goCPT app considers the complexity of data analysis, so including these details enhances the accuracy of the generated codes",
        imgUrl: 'src/assets/codeAccuracy/image5.png',
    },
    {
        head: 'Document Thoroughly with All Relevant Data',
        body: "Ensure that your note incorporates all relevant data, including ordering or reviewing diagnostic test results, imaging studies, and laboratory findings. The goCPT app considers the complexity of data analysis, so including these details enhances the accuracy of the generated codes",
        imgUrl: 'src/assets/codeAccuracy/image6.png',
    },
    {
        head: 'Regularly Update the App',
        body: "Keep the goCPT app updated to ensure you benefit from the latest enhancements and refinements. Regular updates enhance the app's capabilities, providing you with increasingly accurate code suggestions",
        imgUrl: 'src/assets/codeAccuracy/image7.png',
    },
    {
        head: 'Stay Informed',
        body: "Stay abreast of changes in coding guidelines and standards. Familiarize yourself with any updates to CPT codes or relevant regulations. A well-informed approach ensures that your documentation aligns with current coding requirements",
        imgUrl: 'src/assets/codeAccuracy/image8.png',
    }
]

function CodeAccuracy() {
    const AccuracyCards = cardItems.map((item)=>(
        <div key={item.head}>
            <ImageCard head={item.head} body={item.body} imgUrl={item.imgUrl}/>
        </div>
    ))
  return (
    <div className="px-[30px] pb-[100px]">
        <div className="max-w-[1700px] mx-auto w-full bg-gradient-to-b from-[#FFFFFF0D] to-[#FFFFFF00]
            border border-[#FFFFFF33] shadow-featureBox rounded-[30px] backdrop-blur">
                <div className="max-w-[1000px] mx-auto text-center font-jura font-[400] text-white p-[20px]">
                    <h1 className="text-[30px] md:text-[60px]">
                        Ensuring CPT Code Accuracy with <span className="font-[700]">GoCPT</span> App
                    </h1>
                </div>
                <div className="flex flex-wrap justify-center gap-10 p-[20px] my-5">
                    {AccuracyCards}
                </div>
                <div className="max-w-[1400px] mx-auto text-center font-jura font-[400] text-white py-[40px] px-[10px] md:mb-[80px]">
                    <p className="text-[16px]">
                        By incorporating these tips into your practice, you can maximize the accuracy of CPT codes generated by the goCPT app. Remember, your detailed and precise documentation is instrumental in optimizing the app's capabilities and contributing to the overall success of your medical coding and billing processes
                    </p>
                </div>
            </div>
    </div>
  )
}

export default CodeAccuracy
